#!/usr/bin/env python

import signal
import sys
from helpers import credentials
from HTMLParser import HTMLParser
from requests import get

URL = "https://github.com/users/%s/contributions"
NETRC_MACHINE = "github.com"


class CustomHTMLParser(HTMLParser):
    def __init__(self):
        HTMLParser.__init__(self)
        self.rects = []

    def handle_starttag(self, tag, attrs):
        if tag == "rect":
            self.rects.append(attrs)


def signal_handle(sig, frame):
    sys.exit(0)


def pluralize(number):
    if number == 1:
        return ""
    return "s"


def main():
    username, _ = credentials.credentials(NETRC_MACHINE)
    r = get(URL % username)
    parser = CustomHTMLParser()
    parser.feed(r.text)
    d = dict(parser.rects[-1])
    number = d["data-count"]
    date = d["data-date"]
    print("You have %s contribution%s on %s" %
          (number, pluralize(number), date))


signal.signal(signal.SIGINT, signal_handle)
if __name__ == '__main__':
    main()
