#!/usr/bin/env python

import signal
import sys
from helpers import credentials
from requests import get

URL = "https://github.com/users/%s/contributions.json"
NETRC_MACHINE = "github.com"


def signal_handle(sig, frame):
    sys.exit(0)


def pluralize(number):
    if number == 1:
        return ""
    return "s"


def main():
    username, _ = credentials.credentials(NETRC_MACHINE)
    r = get(URL % username)
    json = r.json()
    contributions = json[-1]
    date, number = contributions
    print("You have %s contribution%s on %s" %
          (number, pluralize(number), date))


signal.signal(signal.SIGINT, signal_handle)
if __name__ == '__main__':
    main()
