#!/usr/bin/env python

import signal
import sys
from argparse import ArgumentParser
from helpers import credentials
from json import dumps
from requests import post
from webbrowser import open_new_tab


URL = "https://api.github.com/user/repos"
NETRC_MACHINE = "api.github.com"


def signal_handle(sig, frame):
    sys.exit(0)


def main(options):
    username, password = credentials.credentials(NETRC_MACHINE)
    headers = {'Accept': 'application/vnd.github.v3+json'}
    payload = dumps(options)
    r = post(URL,
             auth=(username, password),
             headers=headers,
             data=payload)
    json = r.json()
    if r.status_code == 201:
        print("Success")
        open_new_tab(json["html_url"])
    else:
        print("Error")
        print(dumps(json, indent=2))


signal.signal(signal.SIGINT, signal_handle)
if __name__ == '__main__':
    parser = ArgumentParser(description="Create a new GitHub repo")
    parser.add_argument("-n", "--name", help="the name of the repo", required=True)
    parser.add_argument("-d", "--description", help="the description of the repo")
    parser.add_argument("-u", "--url", help="the homepage for the repo", dest="homepage")
    parser.add_argument("-p", "--private", action="store_true", help="make the repo private", default=False)
    parser.add_argument("-w", "--wiki", action="store_true", help="enable wikis", default=False, dest="has_wiki")
    parser.add_argument("--no-issues", action="store_false", help="disable issues", default=True, dest="has_issues")
    parser.add_argument("--no-downloads", action="store_false", help="disable downloads", default=True, dest="has_downloads")
    ns = parser.parse_args()
    main(vars(ns))
