#!/usr/bin/env python
#
# Assigns the currently authorized user to a pull request
# Usage: ghb assignme PR_URL
#

from helpers import credentials
from helpers import pr
import argparse
import json
import requests
import sys

NETRC_MACHINE = "api.github.com"
URL = "https://api.github.com/repos/%s/issues/%s/assignees"


def main(pull_request):
    repo, number = pr.extract_info(pull_request)
    user, password = credentials.credentials(NETRC_MACHINE)
    headers = {"Accept": "application/vnd.github.v3+json"}
    params = {"assignees": [user]}
    response = requests.post(URL % (repo, number), auth=(user, password),
                             data=json.dumps(params), headers=headers)
    if response.status_code != 201:
        print(json.dumps(response.json(), indent=4, sort_keys=True))
        sys.exit(1)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Assign yourself to a PR")
    parser.add_argument("pr", help="The PR to assign yourself to")
    arguments = parser.parse_args()

    try:
        main(arguments.pr)
    except KeyboardInterrupt:
        sys.exit(1)
